### ISSUE TITLE
Missing files in CityScapes dataset

### ISSUE THREAD

**Issue by Ali2500** [facebookresearch/instpred#1]
After setting up everything according to SETUP.md and running the inference test on validation data from CityScapes, I get the following error:

> Traceback (most recent call last):
  File "eval.py", line 76, in <module>
    evaluate(evalConfig, model, valLoader)
  File "/globalwork/athar/person-motion-prediction/instpred/evaluation_functions.py", line 148, in evaluate
    for i, data in enumerate(val_loader):
  File "/globalwork/athar/person-motion-prediction/instpred/data_multiscale.py", line 38, in next
    sample = self.data_source[self.current]
  File "/home/athar/anaconda2/envs/fb_instpred/lib/python2.7/site-packages/torchnet/dataset/batchdataset.py", line 101, in __getitem__
    sample = self.dataset[j]
  File "/home/athar/anaconda2/envs/fb_instpred/lib/python2.7/site-packages/torchnet/dataset/transformdataset.py", line 46, in __getitem__
    z = self.dataset[idx]
  File "/globalwork/athar/person-motion-prediction/instpred/cityscapesDatasetAndFeatures.py", line 240, in __getitem__
    seq = self._add_rgb_bgr_features(sample, seqIDs)
  File "/globalwork/athar/person-motion-prediction/instpred/cityscapesDatasetAndFeatures.py", line 266, in _add_rgb_bgr_features
    seq = [np.expand_dims(cv2imread_like(imgID), 0) for imgID in seqIDs] #-- tested to be the same...
  File "/globalwork/athar/person-motion-prediction/instpred/cityscapesDatasetAndFeatures.py", line 43, in cv2imread_like
    im = np.array(Image.open(impath)) # open and convert to np array
  File "/home/athar/anaconda2/envs/fb_instpred/lib/python2.7/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/globalwork/athar/3rdparty/detectron/detectron/datasets/data/cityscapes_sequences/images/frankfurt_000001_014547_leftImg8bit.png'

Running inference for the image file `/work/athar/datasets/Cityscape/leftImg8bit_trainvaltest/leftImg8bit/val/frankfurt/frankfurt_000001_014565_leftImg8bit.png` requires a past sequence of frame images (namely, for this case, 014547, 014550, 014553, 014556, 014559, 014562, 014565), but it seems that aside from the last image, none of the others exist in the CityScape dataset. 

Although not verified, I think this problem will occur on all the images in the CityScape validation set.

**Comment by Ali2500** [comment]
Turns out I'm using the wrong portion of the dataset: the publicly available `leftImg8bit_trainvaltest.zip` archive does not have the aforementioned frames. The `leftImg8bit_sequence_trainvaltest.zip` archive has to be used instead.
