### ISSUE TITLE
issue with running test

### ISSUE THREAD

**Issue by Twizwei** [facebookresearch/instpred#2]
I followed SETUP.md and tried to run 
`python $CAFFE2_PATH/python/operator_test/roi_align_rotated_op_test.py`
for test. However, it turned out that 
`Trying example: test_horizontal_rois(self=<__main__.RoIAlignRotatedOp testMethod=test_horizontal_rois>, H=61, W=75, C=2, num_rois=5, pooled_size=7, gc=device_type: 1, dc=[, device_type: 1])
Traceback (most recent call last):
  File "/home/SelfDriving/miniconda2/envs/instpred/lib/python2.7/site-packages/hypothesis/core.py", line 605, in evaluate_test_data
    result = self.execute(data)
  File "/home/SelfDriving/miniconda2/envs/instpred/lib/python2.7/site-packages/hypothesis/core.py", line 570, in execute
    result = self.test_runner(data, run)
  File "/home/SelfDriving/miniconda2/envs/instpred/lib/python2.7/site-packages/hypothesis/executors.py", line 56, in default_new_style_executor
    return function(data)
  File "/home/SelfDriving/miniconda2/envs/instpred/lib/python2.7/site-packages/hypothesis/core.py", line 568, in run
    return test(*args, **kwargs)
  File "./miniconda2/envs/instpred/lib/python2.7/site-packages/caffe2//python/operator_test/roi_align_rotated_op_test.py", line 28, in test_horizontal_rois
    H=st.integers(min_value=50, max_value=100),
  File "/home/SelfDriving/miniconda2/envs/instpred/lib/python2.7/site-packages/hypothesis/core.py", line 540, in test
    raise DeadlineExceeded(runtime, self.settings.deadline)
DeadlineExceeded: Test took 11371.52ms, which exceeds the deadline of 200.00ms
`
Can anyone help me fix this? Thank you!

**Comment by paulineluc** [comment]
Hi @Twizwei, we provide the installation procedure for Caffe2 and Detectron for convenience. If our procedure does not work for you, please follow theirs and raise any issue on the corresponding repos. Thanks !

**Comment by guptasonam1602** [comment]
@Twizwei I am also facing the same issue. Were you able to solve this?
